baseURL = "https://ericglasser.com/"
languageCode = "en-us"
title = "Eric Glasser"
theme = "hugo-resume"

[params]
    firstName = "Eric"
    lastName = "Glasser"
    address = "Developer Experience Evangelista"
    profileImage = "images/eric_glasser.png"
    email = "eric@ericglasser.com"
    description = "I'm a leading software engineer with over 10 years of experience in the cross-section of technology and business. I'm skilled in full stack development, and have a track record of delivering high-quality solutions that drive business growth. My specialties include developer experience, accessibility, and sustainable software architectures. I have a proven ability to lead cross-functional teams and drive innovation through combining people, process and technology. I'm passionate about staying current with new technologies and trends, and am constantly seeking new challenges and opportunities to learn. Beyond that, I'm someone with a visual impairment who knows firsthand the importance of accessibility and inclusivity in technology."
    # favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/ericglasser/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ericglasser/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/ericglasser/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/2063495/ericglasser"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/ericglasser"
    icon = "key"

[params.google.analytics]
    trackerID = "UA-18770592-7"
