baseURL = "https://ericglasser.com/"
languageCode = "en-us"
title = "Eric Glasser"
theme = "hugo-resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
    firstName = "Eric"
    lastName = "Glasser"
    address = "Denver, CO"
    profileImage = "images/eric_glasser.png"
    email = "eric@ericglasser.com"
    description = "I am a versatile and experienced software engineer with a passion for technology and a holistic approach to problem-solving, focusing on sustainable software architectures and developer experience."
    favicon = "favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showBoards = false
    showCertifications = true
    showSocializations = true
    sections = ["experience", "skills", "education"]

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/ericglasser/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ericglasser/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/2063495/ericglasser"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/ericglasser"
    icon = "key"

[params.google]

[params.google.analytics]
    trackerID = "UA-18770592-7"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
